# Generated by Django 5.1.4 on 2024-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voices',
            name='owner_surname',
            field=models.CharField(default='bilinmiyor', max_length=255),
            preserve_default=False,
        ),
    ]
