# Generated by Django 5.1.4 on 2024-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_voices_owner_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='voices',
            name='owner_surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
