# Generated by Django 5.1.4 on 2024-12-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_voices_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voices',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='mainpage.users'),
        ),
    ]
