# Generated by Django 5.1.4 on 2024-12-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_voices_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voices',
            name='deneme',
        ),
    ]
